language: java
jdk: openjdk6
script: gradle build

notifications:
  email:
    recipients:
      - cvmocanu@gmail.com
      - robert.baboi@gmail.com
    on_success: never # always|never|change
    on_failure: change

